name: Build Docker Images

on: [push]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install basename
        run: sudo apt-get install coreutils

      - name: Pull code from previous commit
        run: git fetch origin "${{ github.event.before }}"

      - name: Log in to the github container registry
        run: echo "${{secrets.GITHUB_TOKEN}}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Get lowercase owner
        run: echo "${{ github.repository_owner }}" | awk '{print "OWNER_LC=" tolower($0)}' >> ${GITHUB_ENV}

      - name: Get changed paths
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs -n 1 dirname | sort | uniq | while read -r PATH; do
            if [ -f "$PATH/Dockerfile" ]; then
              DOCKERFILENAME=$(basename "$PATH")
              LANGUAGE=$(basename $(dirname $(dirname "$PATH")))

              # Sanity check directory
              EXPECTED_PATH="language/${LANGUAGE}/dockerfiles/${DOCKERFILENAME}"
              if [[ "$PATH" != "$EXPECTED_PATH" ]]; then
                echo "The docker file in '$PATH' is not where we expect dockerfiles to be. Skipping"
              fi

              DOCKER_NAME="${LANGUAGE}-${DOCKERFILENAME}"
              DOCKER_TAG="$(date -u +%s)"
              IMAGE_ID="ghcr.io/${OWNER_LC}/${DOCKER_NAME}:${DOCKER_TAG}"
              
              cd $PATH
              docker build . -t "$IMAGE_ID"
              docker push "$IMAGE_ID"
            fi
          done

# The tag will be the current UTC time unix timestamp
# date -u +%s