name: Build Docker Images

on: [push]

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    # outputs
    steps:
      - uses: actions/checkout@v3
      - name: Get changed paths
        run: |
          git fetch origin "${{ github.event.before }}"

          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs -n 1 dirname | sort | uniq

          $CHANGED_FILES | while read -r PATH; do
            echo "=="
            if [ -f "$PATH/Dockerfile" ]; then
              echo "docker File exists. at $PATH"
            else
              echo "File does not exist. at $PATH"
            fi
          done

# The tag will be the current UTC time unix timestamp
# date -u +%s